/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package a2;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class Main {

    public static void main(String[] args){
        JFrame frame = new JFrame("Breakout");

        // setup window
        frame.setPreferredSize(new Dimension(1000,750));
        frame.setMinimumSize(new Dimension(500,375));
        frame.setMaximumSize(new Dimension(1600,1200));
        frame.pack();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setFocusable(false);

        // create Model and initialize it
        if (args.length != 2) {
            System.out.println("Invalid number of arguments");
            System.exit(0);
        }
        int fps = Integer.parseInt(args[0]);
        int ballSpeed = Integer.parseInt(args[1]);
        if (fps < 25 || fps > 60) {
            System.out.println("Choose a FPS value of 25-60!");
            System.exit(0);
        }
        if (ballSpeed < 1 || ballSpeed > 3) {
            System.out.println("Choose a speed value of 1-3!");
            System.exit(0);
        }
        Model model = new Model(frame, fps, ballSpeed);

        // create View, tell it about model (and controller)
        View view = new View(model);
        view.setFocusable(true);
        // tell Model about View.
        model.addObserver(view);

        view.setBorder(BorderFactory.createLineBorder(Color.black));

        frame.add(view);
        frame.setVisible(true);
        view.requestFocusInWindow();
    }
}
